#!/bin/bash
#By wocin
#Email ---
#-------------------I am boring line------------------------------------
cd /etc/yum.repos.d/
wget http://download.openvz.org/openvz.repo
rpm --import http://download.openvz.org/RPM-GPG-Key-OpenVZ
yum update
yum -y install ovzkernel vzctl vzquota
sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/' /etc/sysctl.conf
service iptables stop
setenforce 0
chkconfig iptables off
#-------------------I am boring line------------------------------------
echo '''
# grub.conf generated by anaconda
#
# Note that you do not have to rerun grub after making changes to this file
# NOTICE:  You have a /boot partition.  This means that
#          all kernel and initrd paths are relative to /boot/, eg.
#          root (hd0,0)
#          kernel /vmlinuz-version ro root=/dev/sda2
#          initrd /initrd-[generic-]version.img
#boot=/dev/sda
default=0
timeout=5
splashimage=(hd0,0)/grub/splash.xpm.gz
hiddenmenu
title OpenVZ (2.6.32-042stab083.2)
        root (hd0,0)
        kernel /vmlinuz-2.6.32-042stab083.2 ro root=UUID=0fbe73f0-3267-4770-9edf-a4f20e3c93ae rd_NO_LUKS rd_NO_LVM rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYBOARDTYPE=pc KEYTABLE=us crashkernel=auto rhgb quiet
        initrd /initramfs-2.6.32-042stab083.2.img
title CentOS (2.6.32-358.23.2.el6.x86_64)
        root (hd0,0)
        kernel /vmlinuz-2.6.32-358.23.2.el6.x86_64 ro root=UUID=0fbe73f0-3267-4770-9edf-a4f20e3c93ae rd_NO_LUKS rd_NO_LVM rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYBOARDTYPE=pc KEYTABLE=us crashkernel=auto rhgb quiet
        initrd /initramfs-2.6.32-358.23.2.el6.x86_64.img
title CentOS (2.6.32-71.el6.x86_64)
        root (hd0,0)
        kernel /vmlinuz-2.6.32-71.el6.x86_64 ro root=UUID=0fbe73f0-3267-4770-9edf-a4f20e3c93ae rd_NO_LUKS rd_NO_LVM rd_NO_MD rd_NO_DM LANG=en_US.UTF-8 SYSFONT=latarcyrheb-sun16 KEYBOARDTYPE=pc KEYTABLE=us crashkernel=auto rhgb quiet
        initrd /initramfs-2.6.32-71.el6.x86_64.img
''' > /etc/grub.conf
#-------------------I am boring line------------------------------------
shutdown -r now
cd/vz/template/cache/
wget http://download.openvz.org/template/precreated/centos-6-x86_64.tar.gz
#-------------------I am boring line------------------------------------
vzctl create 10 --ostemplate centos-6-x86_64
vzctl set 10 --onboot yes --save
vzctl set 10 --ipadd 192.168.6.10 --save
vzctl set 10 --nameserver 8.8.8.8 --save
vzctl set 10 --hostname vps.test.com --save
vzctl set 10 --diskspace 10G:10G --save
vzctl start 10
vzctl exec 10 passwd
